#Test variable assignment

func assigntest()
	int a,b,c=100
	int d=c+100
	string n,m="Hello"
	double l=1.4

	if a==0 && b==0 && c==100 && d==200
		println("All is well")
	else
		fail("Variable assignment test1 failed")
	endif

	if n=="" && m=="Hello"
		println("All is well")
	else
		fail("Variable assignment test2 failed")
	endif

	if l>1.3 && l<1.5
		println("All is well")
	else
		fail("Variable assignment test3 failed")
	endif
endfunc

assigntest()
